export const ADD_CUSTOMER_CAMPAIGN = "ADD_CUSTOMER_CAMPAIGN";
export const GET_CUSTOMER_CAMPAIGNS = "GET_CUSTOMER_CAMPAIGNS";
export const GET_CAMPAIGN_BY_ID = "GET_CAMPAIGN_BY_ID";
export const GET_CAMPAIGNS_COUNT_BY_SEGMENT = "GET_CAMPAIGNS_COUNT_BY_SEGMENT";
export const GET_MHNG_ACCOUNT_LIST = "GET_MHNG_ACCOUNT_LIST";
export const SMS_SENDER_ID = "SMS_SENDER_ID";
export const VIBER_SENDER_ID = "VIBER_SENDER_ID";
export const WHATSAPP_SENDER_ID = "WHATSAPP_SENDER_ID";