export const {SERVICE_URL} = process.env
export const ADD_CUSTOMER_SEGMENTS = "ADD_CUSTOMER_SEGMENTS";
export const GET_SEGMENTS = "GET_SEGMENTS";
export const GET_SEGMENTS_BY_ID = "GET_SEGMENTS_BY_ID";
export const UPDATE_SEGMENT = "UPDATE_SEGMENT";
export const GET_CUSTOMERS_BY_SEGMENT = "GET_CUSTOMERS_BY_SEGMENT";
export const GET_CUSTOMERS_COUNT_BY_SEGMENT = "GET_CUSTOMERS_COUNT_BY_SEGMENT";