export const GET_SCHEMA_DATA = "GET_SCHEMA_DATA"; 
export const GET_CUSTOMER_SCHEMA = "GET_CUSTOMER_SCHEMA";
export const GET_EVENT_SCHEMA = "GET_EVENT_SCHEMA";
export const GET_ALL_CUSTOMER_PRODUCTS_SCHEMA = "GET_ALL_CUSTOMER_PRODUCTS_SCHEMA";
export const GET_SCHEDULE_SCHEMA = "GET_SCHEDULE_SCHEMA";
